### ISSUE TITLE
Features request

### ISSUE THREAD

**Issue by Mohamed3nan** [msfrisbie/chat-gpt-assistant#1]
Thank you so much. I recently uninstalled some unnecessary extensions and will depend on this one.
Here are some feature requests that I have in mind:
- A more beautiful icon
[You can see this extension for inspiration](https://github.com/wong2/chat-gpt-google-extension)
- Floating windows/icon (like the ones on customer support sites)
- The ability to create a new line in the prompt
- Google search
[You can see this extension for inspiration](https://github.com/qunash/chatgpt-advanced)

**Comment by msfrisbie** [comment]
[chat-gpt-google-extension](https://github.com/wong2/chat-gpt-google-extension) is the inspiration for this extension!

This extension already supports Google search, as well as other major search engines like Bing, Brave, and DuckDuckGo. The default behavior is to only send the prompt on demand, but this can be changed in settings in 0.4.0

Lots of people are asking for support for folllow-up prompts. This is a WIP!
