### ISSUE TITLE
Suspicious behaviour

### ISSUE THREAD

**Issue by neoOpus** [msfrisbie/chat-gpt-assistant#10]
Why does the new update require to read my history?

![image](https://user-images.githubusercontent.com/1388336/208246654-921766f3-95f1-47b3-9513-e97ce3534005.png)

**Comment by neoOpus** [comment]
I understood from the closed issue that it is related to #7

**Comment by msfrisbie** [comment]
This message is from the "tabs" permission, used to open a new tab and read search terms from url query strings.
