### ISSUE TITLE
31.18MiB? What have you included in the extension?

### ISSUE THREAD

**Issue by wong2** [msfrisbie/chat-gpt-assistant#12]
![image](https://user-images.githubusercontent.com/321947/208682175-751ce757-1931-4c82-8109-585b411e2974.png)

In comparision [ChatGPT for Google](https://chrome.google.com/webstore/detail/chatgpt-for-google/jgjaeacdkonaoafenlfkkkmbaopkbilf) is 163KiB

![image](https://user-images.githubusercontent.com/321947/208682307-51472ca4-cbe1-4e51-a13f-f9ffea73ceb4.png)

**Comment by msfrisbie** [comment]
looks like my parcel got screwed up and didn't tree shake. will fix in next release
