### ISSUE TITLE
Feature Request: On demand or Single Chat Session for all searches.

### ISSUE THREAD

**Issue by patrickcurl** [msfrisbie/chat-gpt-assistant#13]
Since it appears chat histories/sessions are now auto-saved, and having every search in there is annoying. 
Perhaps instead of seaching everytime, instead maybe you do something like add a button to force a search. 

Alternately it might be nice having a saved session that is all previous searches, I'm not sure if it'd be easy to group them using the jailbreak api's or not. This way though, it wouldn't clutter the sidebar.

**Comment by msfrisbie** [comment]
Right click anywhere on a webpage, select "chatgpt assistant settings", and then uncheck "Automatically send prompt when using search engines". This should do the trick!
