### ISSUE TITLE
Add Ecosia to supported search engines

### ISSUE THREAD

**Issue by bastelbert** [msfrisbie/chat-gpt-assistant#3]
Thank's for this great browser extension, works perfect with Brave Search and DuckDuckGo!
It would be great if the plugin would also support Ecosia: https://www.ecosia.org/
While it's not that popular globally, Europeans and especially Germans really like it.
Thank you!

**Comment by msfrisbie** [comment]
Will add in future release!

**Comment by msfrisbie** [comment]
Included in 0.6.0
