### ISSUE TITLE
CMD + Shift + Y does not support Windows and please add a switch to the bright color mode

### ISSUE THREAD

**Issue by CLAY-CMD** [msfrisbie/chat-gpt-assistant#4]

**Comment by msfrisbie** [comment]
Thanks! I'll fix this in an upcoming release

**Comment by CLAY-CMD** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by msfrisbie** [comment]
Will be changing to "Ctrl+Shift+K" in future release
