### ISSUE TITLE
Add an option to close down GPT window when ChatGPT opens up when googling.

### ISSUE THREAD

**Issue by tobiasljunggren97** [msfrisbie/chat-gpt-assistant#6]
It's a great addition but when googling sometimes you're just looking for a random website, and then it would be nice to be able to cancel the GPT query.

**Comment by msfrisbie** [comment]
Will include in future release. For now, there is an option in settings to only execute GPT when a button is clicked

**Comment by msfrisbie** [comment]
Resolved in 0.7.0
