### ISSUE TITLE
Very high CPU usage

### ISSUE THREAD

**Issue by leonardputra** [msfrisbie/chat-gpt-assistant#9]
When enabling this extension, my CPU usage jumps by 30%, the script constantly evaluating something in the background (even when the ChatGPT answer is still waiting). Tested on Google search using Chrome

**Comment by msfrisbie** [comment]
I'm able to replicate. Likely due to re-rendering problems, will investigate further.

**Comment by msfrisbie** [comment]
Mostly resolved in 0.8.3. The continual re-rendering of code containers in markdown isn't solved, but the CPU usage is no longer consistently high.
